JuliaAstro/CFITSIO.jl

Project.toml
src/CFITSIO.jl
test/runtests.jl

The definition of `CFITSIOError` in #3 didn't make it a subtype of `Exception`. This PR fixes this and helps fix downstream test failures in `FITSIO`

CFITSIOError subtypes Exception

---

docs/make.jl
docs/src/index.md
src/CFITSIO.jl
test/runtests.jl

These methods allow one to resize the image, or reinterpret the data as one with a different element type.
```julia
julia> f = fits_clobber_file(tempname());
julia> a = [1 2; 3 4];
julia> fits_create_img(f, a);
julia> fits_write_pix(f, a);
julia> fits_get_img_size(f)
2-element Vector{Int64}:
2
2
julia> fits_resize_img(f, [3,3]);
julia> fits_get_img_size(f)
2-element Vector{Int64}:
3
3
julia> b = similar(a, (3,3));
julia> fits_read_pix(f, b); b
3×3 Matrix{Int64}:
1  4  0
3  0  0
2  0  0
julia> fits_resize_img(f, [4]);
julia> b = similar(a, (4,));
julia> fits_read_pix(f, b); b
4-element Vector{Int64}:
1
3
2
4
```

Add fits_resize_img

---

test/runtests.jl

This PR changes various uses of the `try..finally` pattern in tests to `mktemp`, so that temporary files are automatically removed

Automatically remove temporary files in tests

---

Project.toml
src/CFITSIO.jl
test/runtests.jl

By default CFITSIO uses the extended filename parser, which means that specifications may be appended top the filename in square brackets. This however creates a problem if the filename includes square brackets by itself that don't correspond to specifications. In such cases one may use the `diskfile` functions to skip the extended parser, and use the filename as provided. This solves the issues raised in https://github.com/JuliaAstro/FITSIO.jl/issues/157, and an option to use or not use the extended format parser be added as a feature downstream.
After this PR
```julia
julia> filename = tempname() * "[12].fits"
"/tmp/jl_H5byWY[12].fits"
julia> f = fits_create_diskfile(filename)
FITSFile(Ptr{Nothing} @0x00000000019270a0)
julia> fits_create_img(f, ones(2,2));
julia> fits_write_pix(f, …
```

Add diskfile functions that do not use extended filename parser 

---

Project.toml
test/runtests.jl

Evidently `fits_delete_file` does not ignore errors on closing empty files, as there is a CI failure on master. This PR should fix this.

Bugfix in closing empty files

---

docs/Project.toml
docs/src/index.md

Add doc entries for `fits_create_diskfile` and `fits_open_diskfile` which should resolve links in docs.

Add doc entries for diskfile functions

---

Project.toml
docs/src/index.md
src/CFITSIO.jl
test/runtests.jl

CFITSIO definitions for reference:
<https://heasarc.gsfc.nasa.gov/docs/software/fitsio/c/c_user/node20.html>
Example file to reproduce error:
<https://data.sdss.org/sas/dr18/spectro/sdss/redux/v5_13_2/spectra/lite/3650/spec-3650-55244-0001.fits>
MWE/MRE:
```julia
using FITSIO
fits = FITS("spec-3650-55244-0001.fits")
hdu = fits["SPALL"]
read(hdu, "SPECOBJID")
```
This pr with https://github.com/JuliaAstro/FITSIO.jl/pull/193 will fix error(s) including:
* `KeyError: key 80 not found`
* `MethodError: no method matching cfitsio_typecode(::Type{UInt64})`

Add missing data type (UInt64/Culonglong)

---

.github/workflows/ci.yml

I feel the nightly is too unstable to be tested against as a part of the package CI, and one may always access the `PkgEval` logs if they want to look at test failures on nightly.

Remove tests on julia nightly

---

.github/dependabot.yml

This keeps the CI files updated when the actions have new releases. This should be safe and straightforward to add, and it's being used fairly widely across the julia package ecosystem.

Add dependabot to update CI files

---

src/CFITSIO.jl

My understanding is that this is the way to ensure that the vector is not garbage-collected during the operation, which may lead to segfaults.

Add GC preserve to unsafe_string conversions from pointer

---

src/CFITSIO.jl

This should ensure that the variable isn't freed while a `pointer` to it is being used.

GC_preserve coldefs in create_(binary/ascii)_table

---

src/CFITSIO.jl
test/runtests.jl

This matches the values in https://github.com/HEASARC/cfitsio/blob/01303466dc26cdba256c2fcb44b0f70f3f78912e/fitsio.h#L214-L220. Ideally, we should be reading these in directly from `fitsio.h`, but I don't know how to do that.
Firstly, in `fits_read_errmsg`, the error message is 80 chars, so the array needs to be 81 chars to account for the null terminator. Secondly, `comment` needs to be 73 characters, and not 71, as FITS comments can be up to 72 chars.
I've also added a `GC.@preserve` to `data` in `fits_open_memfile`. This isn't strictly necessary for this PR, but I think this should reduce the chances of errors.

Update max lengths of `UInt8` arrays

---

src/CFITSIO.jl

These are used in generating the functions for the appropriate types. Setting these to `const` probably doesn't matter much, but doesn't hurt anyway.

Set global variables to `const`

---

src/CFITSIO.jl
test/runtests.jl

Uses `PREPEND_PRIMARY` as discussed in #16 . Currently I've hard-coded the value here, which is not ideal. This allows one to insert a new primary HDU and convert the pre-existing one to an image HDU.
```julia
julia> f = fits_create_file(tempname());
julia> a = ones(3);
julia> fits_create_img(f, a); fits_write_pix(f, a);
julia> fits_get_img_size(f)
1-element Vector{Int64}:
3
julia> fits_insert_img(f, Float64, [3,2], true); # insert new primary image
julia> fits_get_hdu_num(f) # check that the current HDU index is still 1
1
julia> fits_get_img_size(f) # the original HDU has been replaced
2-element Vector{Int64}:
3
2
julia> fits_movabs_hdu(f, 2) # the original primary HDU is now an image
:image_hdu
julia> fits_get_img_size(f)
1-element Vector{Int64}:
3
```

Insert a new primary HDU

---

Project.toml
docs/src/index.md
src/CFITSIO.jl
test/runtests.jl

Add the functions `fits_copy_file` that can copy multiple HDUs from one file to another, `fits_copy_hdu` that copies only the current HDU, `fits_copy_header` that copies only the header from the current HDU and appends to the output file, and `fits_copy_data` that copies the data but not the header.

Add HDU and header copy functions

---

src/CFITSIO.jl

This makes the code easier to read.

Change variable T to Clong_or_Clonglong

---

src/CFITSIO.jl
test/runtests.jl

The are low-level functions that allow flushing the current state of the file to disk, without having to close and reopen the file explicitly.

Add `fits_flush_file` and `fits_flush_buffer`

---

docs/src/index.md
src/CFITSIO.jl
test/runtests.jl

This implements the suggestion from https://github.com/JuliaAstro/CFITSIO.jl/issues/19, and creates an empty image with no dimensions. This is useful to create a dummy primary array.

Add `fits_create_empty_img`

---

src/CFITSIO.jl
test/runtests.jl

Currently, we have the `CFITSIO.R` and `CFITSIO.RW` file modes. This adds the equivalent but more verbose `CFITSIO.READONLY` and `CFITSIO.READWRITE` modes, which are easier to read. These match the constants that are defined in the C code. These also parallel astropy, which uses the string "readonly" alongside others.
In addition (although this isn't the most important point), ChatGPT seems to incorrectly suggest `CFITSIO.READONLY` as a valid file mode, and having this available would help with vibe coding.

Add verbose file opening modes

---

docs/src/index.md
src/CFITSIO.jl

Mention `READWRITE` and `READONLY` in docstrings, and fix some incorrect types in the manual.

Improve docstrings and manual

---

src/CFITSIO.jl
test/runtests.jl

Since we are now accepting arbitrary inputs, we need to ensure that they are of the correct type.

Assert types when accepting preallocated arrays

---

src/CFITSIO.jl
test/runtests.jl

Currently, we use two functions `fits_create_binary_tbl` and `fits_create_ascii_tbl` to create tables, but FITSIO calls the lower-level `fits_create_tbl` that accepts the table code as an `Integer`. This PR adds a `fits_create_tbl` wrapper that accepts the table code. We also add an enum of HDU types to make the construction more readable.

Add  `fits_create_tbl` and use in creating tables

---

src/CFITSIO.jl

This preserves the current behavior where the function accepts a `C_NULL` as the `comment` argument.

Accept `Ptr{Nothing}` in `fits_update_key`

---

src/CFITSIO.jl

This adds a wrapper around the C function with the same name. It is only necessary to call this function when the C code allocates memory.

Add `fits_free_memory`

---

Project.toml
src/CFITSIO.jl
test/runtests.jl

CFITSIO allows one to skip the units and extname in creating tables by passing null pointers. In this PR, we allow passing `nothing` to the julia wrappers, which are converted to `C_NULL` in the `ccall`.

Allow skipping units and extname in table creation

---

src/CFITSIO.jl

Since this function already does the same thing, we don't need to reimplement this.

Buffer to `String` using `tostring` in `fits_read_col`

---

src/CFITSIO.jl
test/runtests.jl

This avoids a segfault in writing to an empty fits file. One should create an image HDU first before writing to it.

Ensure that an HDU exists in write

---

Project.toml
src/CFITSIO.jl
test/runtests.jl

This should ensure that we are not accidentally reading invalid memory.

Check for contiguous data and number of pixels

---

test/runtests.jl

These don't seem necessary, and tests pass locally without these.

Remove flushing from tests

---

test/runtests.jl

Add tests for `fits_read_tdim` and `fits_write_tdim`. These write the dimensions of arrays when a table column contains arrays.

Test for reading/writing tdim

---

src/CFITSIO.jl

Clarify that the variables correspond to the dimensions of multidimensional arrays stored in the table column,

Improve read/write_tdim docstrings
